"""create leads table

Revision ID: 30f044d1a014
Revises: 6bda4fa59833
Create Date: 2026-09-19 23:19:25.526929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f044d1a014'
down_revision: Union[str, Sequence[str], None] = '6bda4fa59833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('intent', sa.String(length=500), nullable=True),
    sa.Column('buy_or_rent', sa.Enum('buy', 'rent', name='intent_type'), nullable=True),
    sa.Column('budget', sa.Numeric(precision=13, scale=2), nullable=True),
    sa.Column('location_preference', sa.String(length=500), nullable=True),
    sa.Column('timeline', sa.String(length=200), nullable=True),
    sa.Column('lead_stage', sa.Enum('NEW', 'ENGAGED', 'QUALIFYING', 'QUALIFIED', 'BOOKING', 'BOOKED', 'NURTURE', 'HUMAN_HANDOFF', 'CLOSED', name='lead_stage'), nullable=False),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_organization_id'), 'leads', ['organization_id'], unique=False)
    op.alter_column('properties', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=13, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'price',
               existing_type=sa.Numeric(precision=13, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_leads_organization_id'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
